default:
  push_kubernetes: true
  push_images: true

kubernetes:
  version: v1.28.11


images:
  - docker.io/calico/cni:v3.19.3
  - docker.io/calico/pod2daemon-flexvol:v3.19.3
  - docker.io/calico/node:v3.19.3
  - docker.io/calico/kube-controllers:v3.19.3
  - docker.io/calico/cni:v3.20.6
  - docker.io/calico/pod2daemon-flexvol:v3.20.6
  - docker.io/calico/node:v3.20.6
  - docker.io/calico/kube-controllers:v3.20.6
  - docker.io/flannel/flannel-cni-plugin:v1.4.1-flannel1
  - docker.io/flannel/flannel:v0.25.4
  - registry.k8s.io/ingress-nginx/controller:v1.10.1
  - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.1
  - traefik:v3.0
  
