default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6


images:
  - registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
  - registry.k8s.io/sig-storage/local-volume-provisioner:v2.4.0
